export interface BookCatalogItem {
  id: number;
  usfm: string;
  name_zh: string;
  name_en: string;
  testament: 'OT' | 'NT';
  chapters: number;
}

// Canonical 66-book ordering used by ETL + router mapping.
export const BOOKS: BookCatalogItem[] = [
  [1, 'GEN', '创世记', 'Genesis', 'OT', 50],
  [2, 'EXO', '出埃及记', 'Exodus', 'OT', 40],
  [3, 'LEV', '利未记', 'Leviticus', 'OT', 27],
  [4, 'NUM', '民数记', 'Numbers', 'OT', 36],
  [5, 'DEU', '申命记', 'Deuteronomy', 'OT', 34],
  [6, 'JOS', '约书亚记', 'Joshua', 'OT', 24],
  [7, 'JDG', '士师记', 'Judges', 'OT', 21],
  [8, 'RUT', '路得记', 'Ruth', 'OT', 4],
  [9, '1SA', '撒母耳记上', '1 Samuel', 'OT', 31],
  [10, '2SA', '撒母耳记下', '2 Samuel', 'OT', 24],
  [11, '1KI', '列王纪上', '1 Kings', 'OT', 22],
  [12, '2KI', '列王纪下', '2 Kings', 'OT', 25],
  [13, '1CH', '历代志上', '1 Chronicles', 'OT', 29],
  [14, '2CH', '历代志下', '2 Chronicles', 'OT', 36],
  [15, 'EZR', '以斯拉记', 'Ezra', 'OT', 10],
  [16, 'NEH', '尼希米记', 'Nehemiah', 'OT', 13],
  [17, 'EST', '以斯帖记', 'Esther', 'OT', 10],
  [18, 'JOB', '约伯记', 'Job', 'OT', 42],
  [19, 'PSA', '诗篇', 'Psalms', 'OT', 150],
  [20, 'PRO', '箴言', 'Proverbs', 'OT', 31],
  [21, 'ECC', '传道书', 'Ecclesiastes', 'OT', 12],
  [22, 'SNG', '雅歌', 'Song of Songs', 'OT', 8],
  [23, 'ISA', '以赛亚书', 'Isaiah', 'OT', 66],
  [24, 'JER', '耶利米书', 'Jeremiah', 'OT', 52],
  [25, 'LAM', '耶利米哀歌', 'Lamentations', 'OT', 5],
  [26, 'EZK', '以西结书', 'Ezekiel', 'OT', 48],
  [27, 'DAN', '但以理书', 'Daniel', 'OT', 12],
  [28, 'HOS', '何西阿书', 'Hosea', 'OT', 14],
  [29, 'JOL', '约珥书', 'Joel', 'OT', 3],
  [30, 'AMO', '阿摩司书', 'Amos', 'OT', 9],
  [31, 'OBA', '俄巴底亚书', 'Obadiah', 'OT', 1],
  [32, 'JON', '约拿书', 'Jonah', 'OT', 4],
  [33, 'MIC', '弥迦书', 'Micah', 'OT', 7],
  [34, 'NAM', '那鸿书', 'Nahum', 'OT', 3],
  [35, 'HAB', '哈巴谷书', 'Habakkuk', 'OT', 3],
  [36, 'ZEP', '西番雅书', 'Zephaniah', 'OT', 3],
  [37, 'HAG', '哈该书', 'Haggai', 'OT', 2],
  [38, 'ZEC', '撒迦利亚书', 'Zechariah', 'OT', 14],
  [39, 'MAL', '玛拉基书', 'Malachi', 'OT', 4],
  [40, 'MAT', '马太福音', 'Matthew', 'NT', 28],
  [41, 'MRK', '马可福音', 'Mark', 'NT', 16],
  [42, 'LUK', '路加福音', 'Luke', 'NT', 24],
  [43, 'JHN', '约翰福音', 'John', 'NT', 21],
  [44, 'ACT', '使徒行传', 'Acts', 'NT', 28],
  [45, 'ROM', '罗马书', 'Romans', 'NT', 16],
  [46, '1CO', '哥林多前书', '1 Corinthians', 'NT', 16],
  [47, '2CO', '哥林多后书', '2 Corinthians', 'NT', 13],
  [48, 'GAL', '加拉太书', 'Galatians', 'NT', 6],
  [49, 'EPH', '以弗所书', 'Ephesians', 'NT', 6],
  [50, 'PHP', '腓立比书', 'Philippians', 'NT', 4],
  [51, 'COL', '歌罗西书', 'Colossians', 'NT', 4],
  [52, '1TH', '帖撒罗尼迦前书', '1 Thessalonians', 'NT', 5],
  [53, '2TH', '帖撒罗尼迦后书', '2 Thessalonians', 'NT', 3],
  [54, '1TI', '提摩太前书', '1 Timothy', 'NT', 6],
  [55, '2TI', '提摩太后书', '2 Timothy', 'NT', 4],
  [56, 'TIT', '提多书', 'Titus', 'NT', 3],
  [57, 'PHM', '腓利门书', 'Philemon', 'NT', 1],
  [58, 'HEB', '希伯来书', 'Hebrews', 'NT', 13],
  [59, 'JAS', '雅各书', 'James', 'NT', 5],
  [60, '1PE', '彼得前书', '1 Peter', 'NT', 5],
  [61, '2PE', '彼得后书', '2 Peter', 'NT', 3],
  [62, '1JN', '约翰一书', '1 John', 'NT', 5],
  [63, '2JN', '约翰二书', '2 John', 'NT', 1],
  [64, '3JN', '约翰三书', '3 John', 'NT', 1],
  [65, 'JUD', '犹大书', 'Jude', 'NT', 1],
  [66, 'REV', '启示录', 'Revelation', 'NT', 22]
].map(([id, usfm, name_zh, name_en, testament, chapters]) => ({
  id,
  usfm,
  name_zh,
  name_en,
  testament,
  chapters
} as BookCatalogItem));
